defaults:
    - config
    - _self_

lattice:
    path: ./lattice/sns_ring_nux6.175_nuy6.175_sol.lattice
    seq: rnginjsol
    apertures: false
    foil: false
    impedance:
        xy: false
        z: false
    spacecharge:
        xy: false
        z: false
    rf: false
    solenoid: true

bunch:
    mass: 0.93827231
    energy: 0.800

paint:
    xi: 0.0
    yi: 0.0
    xpi: 0.0
    ypi: 0.0
    
    xf: 0.025
    yf: 0.0
    xpf: 0.0
    ypf: 0.001

turns_inj: 600
turns_store: 0
macros_per_turn: 100
write_bunch_freq: 100
