defaults:
    - config
    - _self_

lattice:
    path: ./lattice/sns_ring_nux6.24_nuy6.15_mad.lattice
    seq: RINGINJ
    apertures: false
    foil: false
    impedance:
        xy: false
        z: false
    spacecharge:
        xy: false
        z: false
    rf: false

bunch:
    mass: 0.93827231
    energy: 1.300

turns_inj: 1044
turns_store: 0
macros_per_turn: 2000
write_bunch_freq: 100
