defaults:
    - config
    - _self_

lattice:
    path: ./lattice/sns_ring_nux6.175_nuy6.175_sol.lattice
    seq: rnginjsol
    apertures: false
    foil: false
    rf: false
    solenoid: true

bunch:
    mass: 0.93827231
    energy: 0.800

amp1: 10.0
amp2: 0.0
phase1: 0.0
phase2: 0.0

turns: 1000